# Generated by Django 5.1.2 on 2024-10-28 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_guide_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='guide',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации'),
        ),
    ]
