# Generated by Django 5.1.2 on 2024-10-30 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_remove_guide_date_posted_guide_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название гайда')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets', verbose_name='Изображение гайда')),
                ('description', models.TextField(verbose_name='Описание гайда')),
                ('creator', models.CharField(max_length=255, verbose_name='Автор')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Гайд', 'verbose_name_plural': 'Гайды'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets', verbose_name='Изображение гайда'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название гайда'),
        ),
    ]
