# Generated by Django 5.1.2 on 2024-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_description_alter_guide_options_alter_guide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets', verbose_name='Изображение описания'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название описания'),
        ),
    ]
