# Generated by Django 5.1.2 on 2024-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_description_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
