# Generated by Django 5.1.2 on 2024-10-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_delete_description_guide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.CharField(max_length=500, verbose_name='URL-фото'),
        ),
    ]
