# Generated by Django 5.1.2 on 2024-10-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название гайда')),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
