# Generated by Django 5.1.2 on 2024-10-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_game_delete_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=500, verbose_name='URL-фото'),
        ),
    ]
